### ISSUE TITLE
bit switch crashes when providing no name

### ISSUE THREAD

**Issue by MrGreenTea** [chriswalz/bit#10]
I get this:
```
❯ bit switch
runtime error: index out of range [-1]
goroutine 1 [running]:
runtime/debug.Stack(0x6aa880, 0xc00000e018, 0xc000061ba8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/chriswalz/bit/cmd.HandleExit()
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.16/cmd/util.go:341 +0xc5
panic(0x6252e0, 0xc0000168a0)
	/usr/local/go/src/runtime/panic.go:969 +0x175
github.com/chriswalz/bit/cmd.RunGitCommandWithArgs(0xc00000c090, 0x1, 0x1)
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.16/cmd/rootShell.go:111 +0x42f
main.main()
	/go/pkg/mod/github.com/chriswalz/bit@v0.4.16/main.go:44 +0x1f9
```

Some info:
```
❯ uname --all
Linux ThinkPad-P53 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
❯ git version --build-options
git version 2.17.1
cpu: x86_64
no commit associated with this build
sizeof-long: 8
❯ bit --version
git version 2.17.1
```

**Comment by sarathsp06** [comment]
@chriswalz looks like the issue is here, the project looks pretty interesting I shall work on this

**Comment by chriswalz** [comment]
Great I think it's a matter of only entering that `if` statement if args > 1 

Down the road I'll make it so that it will show branch suggestions if you type `bit switch` then <ENTER>

**Comment by MrGreenTea** [comment]
> 
> 
> Great I think it's a matter of only entering that `if` statement if args > 1
> 
> Down the road I'll make it so that it will show branch suggestions if you type `bit switch` then

That's actually what I was expecting to happen :)
Thanks for the quick reply and fix!

**Comment by chriswalz** [comment]
@MrGreenTea `bit switch` `bit checkout` `bit co` will now show a list of branches

**Comment by chriswalz** [comment]
<img width="696" alt="Screen Shot 2020-10-09 at 12 45 24 PM" src="https://user-images.githubusercontent.com/6971318/95609813-57eeb580-0a2d-11eb-8e9e-5a8b3fa11ec4.png">
