### ISSUE TITLE
bit save: "EOF found when expecting closing quote" while typing

### ISSUE THREAD

**Issue by philipodev** [chriswalz/bit#102]
**Describe the bug**
`bit save "9:32AM ERR Users/chris/go/src/github.com/chriswalz/bit/cmd/bit_cmd.go:86 >  error="EOF found when expecting closing quote"`
when typing after the first QUOTE-mark in `bit save`

**To Reproduce**
1. run `bit`
2. type `bit save "`
3. now everything you type after starting quote should throw this error.

**Expected behavior**
should probably validate the input once im done typing?

**Screenshots**
![image](https://user-images.githubusercontent.com/28024000/109471723-74899980-7a71-11eb-8eab-7e461f2c241a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Terminal: Ubuntu Terminal
 - Shell: zsh

**Additional context** (Add any other context about the problem here)

**Comment by chriswalz** [comment]
This issue is now fixed in version v1.0.2. Please let me know if you're still having problems. Also, consider donating if you're enjoying using Bit :)
