### ISSUE TITLE
keyboard has no response

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [chriswalz/bit#108]
in any repo
![1](https://user-images.githubusercontent.com/7458713/113103537-f8ca6a80-9231-11eb-9dd3-f7c3133da44b.png)
please select manually, do not type 'bit push'

![2](https://user-images.githubusercontent.com/7458713/113103587-08e24a00-9232-11eb-82e1-b6bed93e69af.png)
keyboard seems to be blocked.

**Comment by chriswalz** [comment]
Hello, what version bit are you using `bit version`

**Comment by ziyouchutuwenwu** [comment]
> Hello, what version bit are you using `bit version`

```sh
$ bit version
bit version v0.8.0
git version 2.31.0
```

**Comment by chriswalz** [comment]
hmm okay can you run `bit update` and let me know if it still doesn't work. This *might have* been fixed in a newer version

**Comment by ziyouchutuwenwu** [comment]
yes, it's ok now, great thanks to your hark work!
