### ISSUE TITLE
Auto completion on zsh does not seem to work (Docker)

### ISSUE THREAD

**Issue by qdm12** [chriswalz/bit#109]
**Describe the bug**: Auto completion does not seem to work when pressing tab

**To Reproduce**

```sh
docker run -it --rm alpine:3.13
# Install zsh
apk add zsh
touch ~/.zshrc
# Install bit
wget -qO- https://gobinaries.com/chriswalz/bit | sh
bit complete
< Press enter >
bit st
< Press tab >
```

**Expected behavior**

Complete `bit st` to `bit status`

**Desktop (please complete the following information):**
 - OS: Alpine container (on Windows host)
 - Terminal: VSCode integrated terminal
 - Shell: Zsh

🙏 forgive me if I'm missing something completely obvious!
❓  Also for feature request, can I open an issue or a pull request? Thinking of adding a `-y` flag to `bit complete` to auto-accept the installation for automated setups. Thanks!

**Comment by qdm12** [comment]
Working by adding `source ~/.zshrc` sorry about that! Should `bit complete` perhaps also source the file it installed its completions in to avoid this issue in the future? 🤔

**Comment by chriswalz** [comment]
Perhaps it should :). Yes feel free to make a PR

**Comment by qdm12** [comment]
Great thanks!

Actually you can use `echo "y" | bit complete` to make it install completions without assistance, but I'll try to do a PR to add a flag to that command 😉
