### ISSUE TITLE
Update process?

### ISSUE THREAD

**Issue by ryanpcmcquen** [chriswalz/bit#11]
When using the curl install method, what is the planned upgrade path for new versions of `bit`? Just re-running that?

**Comment by chriswalz** [comment]
Yep just rerun the curl command

**Comment by ryanpcmcquen** [comment]
Since I use Nushell, I just do this:
```bash -c "curl -sf https://gobinaries.com/chriswalz/bit | sh; curl -sf https://gobinaries.com/chriswalz/bit/bitcomplete | sh && echo y | COMP_INSTALL=1 bitcomplete"```

**Comment by ryanpcmcquen** [comment]
@chriswalz, should we update the README to use that command since it is a bit more shell agnostic?
