### ISSUE TITLE
Alias for git switch does not open branch selector

### ISSUE THREAD

**Issue by ianrobrien** [chriswalz/bit#110]
**Describe the bug**
I have two git aliases set in my `gitconfg`:

```
[alias]
    co = checkout
    sw = switch
```

When I type `bit co` and hit enter, I am able to select my branch.
When I type `bit checkout` and hit enter, I am able to select my branch.
When I type `bit switch` and hit enter, I am able to select my branch.

When I type `bit sw` and hit enter, I get `fatal: missing branch or commit argument`

**To Reproduce**
1. Add the alias `sw = switch` to your `gitconfig`
2. Type `bit sw`

**Expected behavior**
I expect a "dropdown" list of some branches that I can navigate with the up and down arrow keys, or match by typing, in the same way as when I type `bit checkout` or `bit switch`.

**Desktop (please complete the following information):**
 - OS: macOS 11.4 20F71 x86_64
 - Terminal: iTerm2 Build 3.4.8
 - Shell: zsh 5.8

**Comment by chriswalz** [comment]
fixed in c7879cd5b

**Comment by chriswalz** [comment]
Consider donating here: https://github.com/sponsors/chriswalz :)
