### ISSUE TITLE
What does 'bit release' do?

### ISSUE THREAD

**Issue by jyn514** [chriswalz/bit#22]
'Generate a production release' doesn't say very much. Here is the output from running `bit release` offline:

```
$ bit release
Error: accepts 1 arg(s), received 0
$ bit release a
exit status 1
## readme...personal/readme
? Please provide a description of your changes [Enter 2 empty lines to finish] # I hit ctrl+c, because I don't know whether it's referring to the most recent commit or all commits since the latest release
On branch readme
Your branch is up to date with 'personal/readme'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        ...

nothing added to commit but untracked files present (use "git add" to track)
ssh: Could not resolve hostname github.com: Temporary failure in name resolution
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ssh: Could not resolve hostname github.com: Temporary failure in name resolution
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
If `bit` is going to perform arbitrary git operations, I'd like to at least know what they are.

**Comment by chriswalz** [comment]
Examples for until the docs are updated

Usage: `bit release bump`: this command commits any changes (except untracked), bumps the minor tag the branch according to SemVer e.g. v0.1.2 -> v0.1.3) and pushes

Usage 2: `bit release v0.6.0` -> this would do the same as above except the tag would be v0.6.0.

**Comment by jyn514** [comment]
Does it also push tags?

**Comment by chriswalz** [comment]
yep both the commit and tags

**Comment by SolKuczala** [comment]
Hi, as I didn't find any other place to reach you out, I would like to ask you if for this issue it needs to have more details in the short description in the cmd package or is something else. Also, as I didn't find documentation about how to contribute, I would like to know how to build the binary on my machine (go run main.go or something else?) to see the changes. Thank you :)

**Comment by chriswalz** [comment]
@SolKuczala clone the repo & run `go run main.go`. I'm personally using go 1.15 but it should be fine with prior versions. 

I'll try to get around to writing a contributing doc. Please let me know if you have any additional questions

**Comment by chriswalz** [comment]
@jyn514 updated `bit release` doc with 39d807e24c5be4fc081e29623ed09d0dd13d497c
