### ISSUE TITLE
Autocompletion menu not appearing in zsh

### ISSUE THREAD

**Issue by chris-aeviator** [chriswalz/bit#30]
I've installed "the hard way", can confirm bit works, but the autocomplettion menu will just not appear. 

Arch linux
❯ zsh --version
zsh 5.8 (x86_64-pc-linux-gnu)

**Comment by pietrovismara** [comment]
Same issue in Linux Mint with terminator 1.91

**Comment by chriswalz** [comment]
To clarify, if you type `bit` and then press <enter> do suggestions show? Or are you referring to classical command tab completion?

**Comment by NightMachinary** [comment]
It doesn't work for either; I'm using Aloxaf/fzf-tab though.
![image](https://user-images.githubusercontent.com/36224762/95757936-a366c500-0cb4-11eb-9cd9-22c25ff9a0fb.png)

- No description of the options
- `-all` instead of `--all`

**Comment by pietrovismara** [comment]
@chriswalz sorry for the noise, it actually works fine for me now.

**Comment by chriswalz** [comment]
@pietrovismara what did you change/fix to make it work?

**Comment by pietrovismara** [comment]
@chriswalz Not much, just rebooted my pc for unrelated reasons and bit was working fine after that.

**Comment by sbmueller** [comment]
I have the same issue on zsh and bash.

**Comment by chriswalz** [comment]
@sbmueller just pushed a couple of updates. 

Run `bit --version`

Can you run naked `bit` and show me the output

Also can you type `bit st` then press `<tab>` and show me the output

**Comment by chris-aeviator** [comment]
@chriswalz btw. `bit --version` will only work in a folder that contains a git repository

**Comment by chris-aeviator** [comment]
I tried updating (the hardway), ended up with `bit --version` -> v.0.6.2.

downloaded from github releases
```
❯ wget https://github.com/chriswalz/bit/releases/download/v0.6.2/bit_0.6.2_Linux_x86_64.tar.gz
❯ tar -zxvf bit_0.6.2_Linux_x86_64.tar.gz
❯ ./bit --version
bit version v0.6.1
git version 2.26.2

```

**Comment by chris-aeviator** [comment]
re-opening since it only worked in the folder that I did a `git init` in order to have `bit --version` work. When changing to a already existing git folder, it will not show the autocompletion popup.

![grafik](https://user-images.githubusercontent.com/11522213/96091226-9ec72a00-0ec9-11eb-9474-f6049f23abfb.png)

**Comment by sbmueller** [comment]
@chriswalz I was just trying on my home machine and realized I used `bit` wrong. I assumed the autocompletion menu appears already when typing `bit ` but I gotta run `bit` first to get the autocompletion.
I will test again next week on my work machine.

I have the same issue as @chris-aeviator with running `bit` outside a repository.

**Comment by sbmueller** [comment]
As expected, my issue is resolved and originated from wrong usage.
@chriswalz kudos to the great support and high activity in this project!

**Comment by chriswalz** [comment]
@sbmueller what was wrong about the your usage. I can clarify that in the readme in case others have the same problem

**Comment by sbmueller** [comment]
@chriswalz I assumed typing `bit ` would lead the autocompletion menu to pop up, however I need to execute the `bit` command (basically press enter additionally) to start the program and get the autocompletion menu.

**Comment by chris-aeviator** [comment]
I assumed the same - can confirm I see autocomplete menu also when going the `bit <Enter>` route.

Is there any way of making this work on `bit <Tab>` ? It's a bit of a pain to run a command twice I'll use 40 times a day.

**Comment by chriswalz** [comment]
@chris-aeviator I'm not sure what you mean by having to run the a command twice as much. Using <Enter> instead of <Tab> doesn't result in more button presses. 

Also note you can always run commands normally with classical tab completion i.e. `bit checkout <branch-name>`

In terms of replacing <Enter> with <TAB> . Not sure if that's possible as of yet

**Comment by nitin88** [comment]
I am actually facing the same issue. Not sure what worked for others.
Just installed it and ran `bit completion && bit` and post that I don't see any tab completions appearing

**Comment by chriswalz** [comment]
@nitin88 run `bit complete && bit;`

**Comment by nitin88** [comment]
> @nitin88 run `bit complete && bit;`

I did, still didn't work for me.
I had to reload `~/.zshrc` to make it work.
