### ISSUE TITLE
Interactive prompt completion does not display suggestions

### ISSUE THREAD

**Issue by edoreld** [chriswalz/bit#35]
I'm using macOS Catalina (10.15.7) and iTerm2 (3.3.2)

I installed `bit` through cURL:

```
curl -sf https://gobinaries.com/chriswalz/bit | sh;
curl -sf https://gobinaries.com/chriswalz/bit/bitcomplete | sh && echo y | COMP_INSTALL=1 bitcomplete
```

Autocompletion works but interactive suggestions don't show. Any ideas?

**Comment by chriswalz** [comment]
Type "bit" and press enter

Or "bit checkout" and press enter

**Comment by edoreld** [comment]
Thanks, it works.
