### ISSUE TITLE
invalid github.com/

### ISSUE THREAD

**Issue by Therealchainman** [chriswalz/bit#39]
I am getting this error when I follow the hard method for getting bit on WSL1 for Windows 10.  
golang 1.15.2
input
```sudo GO111MODULE=on go get github.com/chriswalz/bit@latest;```
I get permission denied if I don't sudo. 
Output
```package github.com/chriswalz/bit@latest: invalid github.com/ import path "github.com/chriswalz/bit@latest"```

**Comment by chriswalz** [comment]
@Therealchainman Were you able to resolve this. There's not much I can do on my end. Any additional information you can provide?

**Comment by Therealchainman** [comment]
I will try again today with Go version 1.12 I don't know if that will work though.  I believe this uses 1.15.  
I suspect there is was something wrong with my GOPATH originally, which I've fixed so maybe it will work when I try 1.15.
Basically I had just installed Go and GOPATH points to $HOME/go, but this had same file structure as GOROOT.  I had to rm -r the directory and create go/{src,bin,pkg} there for the GOPATH file structure.

**Comment by Therealchainman** [comment]
These are the results as someone new to Go.  I just installed Go 3 days ago.  I installed Go on WSL1 on Windows 10.   I was getting something with GOPATH is detected as GOROOT.  I fix this by emptying the GOPATH and adding directory {src,pkg,bin}.  After that that installation of bit was a success with Go Version 1.12 on WSL1.

**Comment by chriswalz** [comment]
@Therealchainman Thanks for updating the issue. It will be useful to see how you did it in case anyone else runs into the same problem
