### ISSUE TITLE
Getting runtime error

### ISSUE THREAD

**Issue by siva-sundar** [chriswalz/bit#42]
Getting runtime error after running cmd `bit`.

System Software Overview:

      System Version: macOS 10.15.6 (19G73)
      Kernel Version: Darwin 19.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled

![image](https://user-images.githubusercontent.com/15258941/95941847-56dbd080-0dff-11eb-83cd-fe737aeba16d.png)

**Comment by chriswalz** [comment]
what version of git do you have?

**Comment by chriswalz** [comment]
Please re-install and it should be fixed
