### ISSUE TITLE
bit log

### ISSUE THREAD

**Issue by veksha** [chriswalz/bit#43]
bit log 
Branch was fast-forwarded

is it a bug?

**Comment by chriswalz** [comment]
@veksha on certain commands bit will check to make your branch is up to date. It saw you were behind the upstream/origin branch and did a `git pull --ff-only`. So yes it's a feature. However if this is confusing or you think it should be changed in some way let me know

**Comment by veksha** [comment]
@chriswalz the problem is that it never displays a log. additionally it triggers pull command even if my branch is up to date.

**Comment by chriswalz** [comment]
Oh understood this is a bug

**Comment by chriswalz** [comment]
fix ad6830f6d9b106386d4ac3139a8a992d51107bec

**Comment by chriswalz** [comment]
(not released yet)

**Comment by chriswalz** [comment]
@veksha should be fixed now. Please re-install

**Comment by veksha** [comment]
@chriswalz it works now. thank you!
