### ISSUE TITLE
err: strconv.Atoi: parsing "": invalid syntax

### ISSUE THREAD

**Issue by jyn514** [chriswalz/bit#48]
**Describe the bug**

`bitcomplete` errors instead of adding completions.

**To Reproduce**

```
$  GO111MODULE=on go get github.com/chriswalz/bit@latest;
go: finding github.com/chriswalz/bit v0.6.1
go: downloading github.com/chriswalz/bit v0.6.1
go: extracting github.com/chriswalz/bit v0.6.1
$ COMP_INSTALL=1 bitcomplete;
COMP_LINE  COMP_POINT  err: strconv.Atoi: parsing "": invalid syntax
```

**Expected behavior**

`bitcomplete` installs completions.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Terminal: LXTerminal
 - Shell: bash

**Additional context** (Add any other context about the problem here)

HEAD is currently https://github.com/chriswalz/bit/commit/5728e0674490ff8665e74b969778065644d77781.

**Comment by chriswalz** [comment]
Sorting out some tricky compatibility issues with `bitcomplete`. Mind giving the install a shot again? I pushed a hotfix v0.6.2

**Comment by jyn514** [comment]
That fixed it, thanks!
