### ISSUE TITLE
any plans to support l10n?

### ISSUE THREAD

**Issue by markruler** [chriswalz/bit#49]
The difficulty of using git for the first time was that it was hard to read English explanations. It would be nice if bit would solve this. It will be good for beginners. (Perhaps the contributors will help translate)

**Comment by markruler** [comment]
@chriswalz 
😓 Sorry, It's not a bug. Please remove the label.

**Comment by chriswalz** [comment]
Git provides translations. This issue #47 is related to non-english Git.

**Comment by chriswalz** [comment]
Bit currently uses English Git so there is work to be done on that front
