### ISSUE TITLE
Please provide another install method than curl | sh

### ISSUE THREAD

**Issue by duckunix** [chriswalz/bit#5]
Please update the README with alternative install instructions.

curl <uri> | sh is not really secure, automatable, or auditable.

Thank you

**Comment by chriswwalz** [comment]
Any suggestions for good alternatives? [goreleaser](https://github.com/goreleaser/goreleaser) seems solid

**Comment by duckunix** [comment]
I am not a Go developer, so I do not know the normal Go tools, but other Go projects I follow use `go get -u`.  An example is over at https://github.com/skx/rss2email

**Comment by chriswalz** [comment]
Closed via 6075b951139eca410a9408d1e301d4363c5c285b

**Comment by duckunix** [comment]
Thank you!
