### ISSUE TITLE
Bit --version should be callable in folders that do not have a `.git` folder inside 

### ISSUE THREAD

**Issue by chris-aeviator** [chriswalz/bit#51]
**Describe the bug**
When running `bit --version` in a non-git folder
```
❯ bit --version
fatal: not a git repository (or any of the parent directories): .git
```

**To Reproduce**
1. Install bit
2. create an arbitrary directory `mkdir /tmp/prettyArbitrary`
3. `cd /tmp/prettyArbitrary`
4. `bit --version`

**Expected behavior**
Bit should output it's version despite the folder it being run from is not a git folder 

**Desktop (please complete the following information):**
 - OS: Arch 
 - Terminal: allacritty 
 - Shell: zsh

**Additional context** 
as mentioned in https://github.com/chriswalz/bit/issues/30

**Comment by shiv6146** [comment]
@chriswalz I have tried to fix this issue in my PR. Can you please review ? Thanks :+1:

**Comment by chriswalz** [comment]
I'll take a look at it today or tomorrow. Thanks for helping out
