### ISSUE TITLE
is there an option to show the git commands being executed?

### ISSUE THREAD

**Issue by opensas** [chriswalz/bit#54]
I'm giving a try to bit, and I'm using `bit sync` to `git pull`

Is there some option to show the git command being executes when i run `bit sync` 

If not, it would be a nice feature to have. In case something goes wrong, you can be sure what was executed and google around to fix it.

**Comment by chriswalz** [comment]
bit sync will output the results of the command that it runs but doesn't print what the  commands actually are. I'd like to add a debug mode at some point so it would make sense to as it as part of that

**Comment by opensas** [comment]
yes that would be a grat enhacement
