### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by patrickhener** [chriswalz/bit#57]
**Describe the bug**
Nothing is displayed at all. No dropdown and nothing

**To Reproduce**
bit <enter> <up> <down> <something>

**Expected behavior**
Show colorful dropdown

**Desktop (please complete the following information):**
 - OS: Arch linux 5.8.14-arch1-1
 - Terminal: gnome-terminal
 - Shell: zsh 5.8 (x86_64-pc-linux-gnu), oh-my-zsh, p10k

**Additional context** (Add any other context about the problem here)

**Comment by chriswalz** [comment]
You must type `bit` and then press <ENTER>

**Comment by patrickhener** [comment]
Well I am really dump ^^ I tried it outside a git repository. So sorry for wasting your time.

**Comment by chriswalz** [comment]
no worries. We're going to make this a bit more clear in the README
