### ISSUE TITLE
Install issues for windows

### ISSUE THREAD

**Issue by kapteynpeter** [chriswalz/bit#6]
Looks like should support windows, but the install instructions haven't been working for me. 
```
$ curl -sf https://gobinaries.com/chriswalz/bit | sh;

  ==> Downloading github.com/chriswalz/bit@master
  ==> Resolved version master to v0.4.10
  ==> Downloading binary for windows amd64

  ==> Permissions required for installation to /usr/local/bin — alternatively specify a new directory with:
  ==>   $ curl -sf https://gobinaries.com/github.com/chriswalz/bit@v0.4.10 | PREFIX=. sh
main: line 184: sudo: command not found
```

using git bash on windows 10

**Comment by chriswalz** [comment]
I'll be working on getting Windows better supported over the next couple of days 

- with that said you can install it this way

## Windows Installation
[Install Go](https://golang.org/dl/)
`go get -u github.com/chriswalz/bit;`

Bash Tab completion is not yet support for Windows

**Comment by kapteynpeter** [comment]
Thanks for the response! 

This is a sweet project. Saw it on tldr this morning.

**Comment by chriswalz** [comment]
@kapteynpeter Can you send me a link? I haven't heard of tldr

Let me know if you run into any other issues

**Comment by kapteynpeter** [comment]
Yeah it's like a tech news daily email. 

![Screenshot_20201007-191605.jpg](https://user-images.githubusercontent.com/55260531/95397675-d1719100-08d1-11eb-9602-962ff4c7ef86.jpg)

I don't have a link but it's pretty big.
