### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by edoreld** [chriswalz/bit#60]
**Describe the bug**
Error appears on running bit command

**To Reproduce**
1. Download Bit 0.7.5 on Mac with the curl instructions
2. Run bit

**Expected behavior**
bit runs with no error

**Screenshots**
<img width="518" alt="Screenshot 2020-10-20 at 08 33 41" src="https://user-images.githubusercontent.com/973854/96548984-212b6180-12af-11eb-8d40-c90ed7199808.png">

**Desktop (please complete the following information):**
 - OS: 10.5.7
 - Terminal: iTerm2
 - Shell: zsh 5.8

**Additional context** (Add any other context about the problem here)

**Comment by chriswalz** [comment]
@edoreld Thanks, for filing this. This error occurs when running outside a git repo. You *should* be able to run `bit update` which upgrade you to `v0.7.7` which fixes this issue :)

**Comment by edoreld** [comment]
Thanks, updating fixed it.
