### ISSUE TITLE
Doesn't work very well with light color scheme

### ISSUE THREAD

**Issue by Hultner** [chriswalz/bit#62]
**Describe the bug**
Text is almost unreadable or completely unreadable in a dozen or so different light color schemes from the popular base16 framework for terminal/syntax colours. Tried a dozen or so light color-schemes and only one were somewhat readable.

**To Reproduce**
1. Pick a color scheme such as base16_github, grayscale-light, solarized light, one-lighter, papercolor-light, material-lighter, classic-light, atelier-cave-light
2. Start bit
3. Try to read text
4. See unreadable text, no text or similar

**Expected behavior**
Text that's readable, configuration for a more basic light theme would be fine.

**Screenshots**
Didn't screenshot them all but here's a few that exhibit said problem.

<img width="366" alt="Screenshot 2020-10-26 at 22 19 25" src="https://user-images.githubusercontent.com/2669034/97230217-dee7b000-17d9-11eb-803e-b09041cb2f00.png">
<img width="865" alt="Screenshot 2020-10-26 at 22 18 22" src="https://user-images.githubusercontent.com/2669034/97230218-df804680-17d9-11eb-8db2-16bdb4278947.png">
<img width="833" alt="Screenshot 2020-10-26 at 22 17 11" src="https://user-images.githubusercontent.com/2669034/97230219-e018dd00-17d9-11eb-81c0-d63030b0c768.png">
<img width="776" alt="Screenshot 2020-10-26 at 22 16 36" src="https://user-images.githubusercontent.com/2669034/97230221-e0b17380-17d9-11eb-8e93-61439af3368f.png">
<img width="763" alt="Screenshot 2020-10-26 at 22 16 26" src="https://user-images.githubusercontent.com/2669034/97230224-e14a0a00-17d9-11eb-983d-e4927f2ae8ba.png">
<img width="726" alt="Screenshot 2020-10-26 at 22 15 43" src="https://user-images.githubusercontent.com/2669034/97230226-e14a0a00-17d9-11eb-8d4d-b86ad05ac8f5.png">
<img width="776" alt="Screenshot 2020-10-26 at 22 15 01" src="https://user-images.githubusercontent.com/2669034/97230227-e1e2a080-17d9-11eb-8165-cde98adcca16.png">
<img width="811" alt="Screenshot 2020-10-26 at 22 13 17" src="https://user-images.githubusercontent.com/2669034/97230212-dd1dec80-17d9-11eb-9003-89109e753736.png">

**Desktop (please complete the following information):**
 - OS:  64bit Mac OS X 10.15.7 19H2  x86_64 Darwin 19.6.0
 - Terminal: iterm
 - Shell: zsh

**Additional context** (Add any other context about the problem here)
As mentioned above, I'd be happy with a more simple monochrome that's configurable that works with light color-schemes as well. Of course the ideal would be support for actually base16_shell themes like a lot of "modern" cli tools got. But a simpler fallback for light color scheme users without base16 would still be desirable.

**Comment by chriswalz** [comment]
@Hultner Thanks for filing this issue. Agreed that bit can be difficult to read in some contexts. Currently, I'd like to avoid config files if possible. 

One option is to have "absolute" colors that don't change due to the background however AFAIK that's not possible with https://github.com/c-bata/go-prompt. 

Another option is to have two themes a light & dark them that changes based on the terminal background color. Surprisingly this isn't possible with all terminals AFAIK.

**Comment by Hultner** [comment]
A popular tool with "pretty" syntax that handles this quite nicely is bat[1], they use a $BAT_THEME environment variable which in my opinion is much nicer than a configuration file. They also have built in support of base16. 

I'm not very familiar with go but a quick search turned up [this library](https://pkg.go.dev/github.com/belak/base16-builder-go), might not be useful but I'll leave it here anyway 


[1]: https://github.com/sharkdp/bat#highlighting-theme

**Comment by chriswalz** [comment]
I've added an experimental "inverted" theme. To enable set your env variable:

`BIT_THEME=inverted`

**Comment by Hultner** [comment]
Is this released yet? it still looks just as bad on bit v0.8.2
<img width="678" alt="image" src="https://user-images.githubusercontent.com/2669034/97541024-c091d800-19c4-11eb-83a2-0fd240eca9df.png">

**Comment by chriswalz** [comment]
![image](https://user-images.githubusercontent.com/6971318/97610290-111c2c00-19eb-11eb-80d8-3862738427ca.png)

![image](https://user-images.githubusercontent.com/6971318/97610371-27c28300-19eb-11eb-8cf9-e8ead8005dcd.png)

![image](https://user-images.githubusercontent.com/6971318/97610430-3a3cbc80-19eb-11eb-86dd-ea99ee0bd3af.png)

![image](https://user-images.githubusercontent.com/6971318/97610471-49236f00-19eb-11eb-80bd-64b97a2e4fda.png)

**Comment by chriswalz** [comment]
I guess on your end it's the "Selected" color that is problematic. It's possible some colors aren't getting set

**Comment by Hultner** [comment]
I've never coded go but I might be able to give it a go and see if I can create something reasonable looking if the build tool chain is easy/fast to set up.

**Comment by chriswalz** [comment]
Yes, definitely take a look. Look for the function `SuggestionPrompt(` in `util.go`.

Once you clone or fork the repo & install go. run `BIT_THEME=inverted go run main.go`

**Comment by Hultner** [comment]
@chriswalz I gave it a _go_ (some _Go_thenburg humour right there), I made two themes to compare, I think it might turn out better this way since it's not always the same theme that works everywhere. Anyway here's a first screenshot. I took them with night shift on at first so I'm redoing the other colour themes without to give a good picture of how it looks.

![Uploading Screenshot 2020-10-29 at 21.23.42.png…]()

**Comment by Hultner** [comment]
Okay here's a full load of screenshots, I didn't test everything but at least of these two additional themes is readable on every combination I've tried, a good dozen of teams seems reasonable.

<img width="2560" alt="Screenshot 2020-10-29 at 21 23 42" src="https://user-images.githubusercontent.com/2669034/97629441-66c5f800-1a2e-11eb-9d6b-84b40a0fa6cc.png">,
<img width="2560" alt="Screenshot 2020-10-29 at 21 23 29" src="https://user-images.githubusercontent.com/2669034/97629443-675e8e80-1a2e-11eb-9dc3-68d06fceb690.png"> 
<img width="2560" alt="Screenshot 2020-10-29 at 21 23 22" src="https://user-images.githubusercontent.com/2669034/97629444-675e8e80-1a2e-11eb-80f3-5535e19fd75a.png">


.
<img width="2560" alt="Screenshot 2020-10-29 at 21 23 17" src="https://user-images.githubusercontent.com/2669034/97629427-63327100-1a2e-11eb-89e0-c423cf4508ca.png">
<img width="2560" alt="Screenshot 2020-10-29 at 21 31 17" src="https://user-images.githubusercontent.com/2669034/97629429-64639e00-1a2e-11eb-8c08-a08d62c0aa2f.png">
<img width="2560" alt="Screenshot 2020-10-29 at 21 30 30" src="https://user-images.githubusercontent.com/2669034/97629431-64fc3480-1a2e-11eb-910a-516ae3f4a191.png">
<img width="2560" alt="Screenshot 2020-10-29 at 21 30 25" src="https://user-images.githubusercontent.com/2669034/97629432-64fc3480-1a2e-11eb-8ecb-628233f0c934.png">
<img width="2560" alt="Screenshot 2020-10-29 at 21 29 41" src="https://user-images.githubusercontent.com/2669034/97629435-6594cb00-1a2e-11eb-9d23-8ca7794d3ccc.png">
<img width="2560" alt="Screenshot 2020-10-29 at 21 28 56" src="https://user-images.githubusercontent.com/2669034/97629437-6594cb00-1a2e-11eb-9269-bed0c13597fa.png">
<img width="2560" alt="Screenshot 2020-10-29 at 21 27 44" src="https://user-images.githubusercontent.com/2669034/97629438-662d6180-1a2e-11eb-8808-6def5639630f.png">
<img width="2560" alt="Screenshot 2020-10-29 at 21 27 30" src="https://user-images.githubusercontent.com/2669034/97629440-66c5f800-1a2e-11eb-966b-eed15b00d593.png">
<img width="2560" alt="Screenshot 2020-10-29 at 21 34 32" src="https://user-images.githubusercontent.com/2669034/97629563-9248e280-1a2e-11eb-9622-bb1f0257b4a5.png">

<img width="2560" alt="Screenshot 2020-10-29 at 21 34 21" src="https://user-images.githubusercontent.com/2669034/97629554-9117b580-1a2e-11eb-9b43-a045b2076664.png">

**Comment by Hultner** [comment]
@chriswalz Added a PR #71
