### ISSUE TITLE
Add a way to get version of installed `bit` instance

### ISSUE THREAD

**Issue by yermulnik** [chriswalz/bit#74]
**Describe the bug**
There's not way to get the version of already installed `bit` instance.

**To Reproduce**
Install `bit`

**Expected behavior**
There is a command line argument to query `bit` instance for its version. Argument should not interfere with `git` CLI and shouldn't be passed on to it.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6 x86_64
 - Terminal: iTerm2 3.3.12
 - Shell: GNU bash, version 5.0.18(1)-release (x86_64-apple-darwin19.5.0)

**Additional context** (Add any other context about the problem here)
First reported in #63

**Comment by chriswalz** [comment]
This was possible with `bit --version` I added `bit version` well. They now show as suggestions

**Comment by yermulnik** [comment]
@chriswalz Thank you! I seem to think `bit version` showed me `git` version only previously.
