### ISSUE TITLE
`bit update`: check whether update is needed

### ISSUE THREAD

**Issue by yermulnik** [chriswalz/bit#77]
**Describe the bug**
`bit update` doesn't check its version of the installed binary but re-downloads itself over again

**To Reproduce**
Run `bit update` and watch it updating from latest to latest version.

**Expected behavior**
`bit update` compares installed version to latest and downloads update only when needed.

**Screenshots**
```
> sudo bit update
Bit is supported through donations. Consider donating here: ❤ https://github.com/sponsors/chriswalz
Updated bit 0.9.1 to v0.9.1 in /usr/local/bin
```

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6 x86_64
 - Terminal: iTerm2 3.3.12
 - Shell: GNU bash, version 5.0.18(1)-release (x86_64-apple-darwin19.5.0)

**Additional context** (Add any other context about the problem here)
First reported in #63

**Comment by chriswalz** [comment]
This may be due to the symlink issue since bit update does/should check.

**Comment by chriswalz** [comment]
This was a bug related to when versions are something without a "v" in SemVer

**Comment by yermulnik** [comment]
@chriswalz Thank you!
