### ISSUE TITLE
homebrew not found the formula

### ISSUE THREAD

**Issue by Sirormy** [chriswalz/bit#79]
Is need tap action beform installing?

**Comment by chriswalz** [comment]
@Sirormy nope. It's part of `homebrew-core`. I just tested and it seems fine. Perhaps use the curl installation if you're having problems

**Comment by einsteinx2** [comment]
@chriswalz I can confirm I'm seeing the same issue (I'm on the latest Catalina 10.15.7) with updated Homebrew:

```
ben-mbp-wifi :: ~/workspacex/LocalMusicPlayer ‹git master› » brew update    1 ↵
Already up-to-date.
ben-mbp-wifi :: ~/workspacex/LocalMusicPlayer ‹git master› » brew install bit-git
Updating Homebrew...
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "bit-git".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by chriswalz** [comment]
@einsteinx2 Very interesting, thanks for the update. @Sirormy let us know if @einsteinx2's solution works

**Comment by Sirormy** [comment]
@chriswalz @einsteinx2 Thanks for answering, I found my homebrew not worked well, I just reinstalling that, and now it worked 😄
