### ISSUE TITLE
feature: open command

### ISSUE THREAD

**Issue by joe-getcouragenow** [chriswalz/bit#88]
after doing a push to my fork to create a PR, i normally open the URL to it.

I have all this as a makefile include.

So i was wondering if you can add a "push and open" ?

**Comment by chriswalz** [comment]
Can you walk me through the commands that you run? And also what you would like the `bit` command to look like?

E.g. 

## Current Workflow

...

## Proposed Bit Open Workflow

..

**Comment by chriswalz** [comment]
Closing this until there's a response
