### ISSUE TITLE
Install Enhancement : brew install bit

### ISSUE THREAD

**Issue by roeniss** [chriswalz/bit#9]
actually, `bit` is taken already : https://formulae.brew.sh/formula/bit

but still we can get some brew integration.

I suggested this idea because I prefer to use Homebrew package management.

**Comment by roeniss** [comment]
if this makes sense please reply. I think i can make it even though i never did such a stuff.

**Comment by chriswalz** [comment]
So would we need something like `bitcli`?

**Comment by chriswalz** [comment]
Cool, let's use `bit` then with taps.  If there's anything I need to do on my end let me know. 

If there's any sort of account creation etc. I'd like to control those aspects of course

**Comment by roeniss** [comment]
cool. of course you deserve it. I'll report a progress in a week.

**Comment by roeniss** [comment]
@chriswalz `bit` is released to gobinaries.com by goreleaser automatically, right?

If so, I'll integrate brew deployment cycle with goreleaser too after I tested manual way

**Comment by tsujp** [comment]
Would you guys need hosting for the tap? If so I volunteer as tribute.

**Comment by chriswalz** [comment]
@tsujp I'm not familar with the process – why is hosting necessary? My cursory reading made it seem to me like we would need a git repo only

**Comment by dawidd6** [comment]
Yes, only a repository on GitHub is enough. Goreleaser supports publishing to a tap:
https://goreleaser.com/customization/homebrew/

**Comment by chriswalz** [comment]
Great. It would be nice to integrate with Goreleaser since we're already using that

**Comment by roeniss** [comment]
you say you would help `bit` with coding `Goreleaser`, @dawidd6? What do you mean "hosting"?

**Comment by chriswalz** [comment]
@roeniss in reference to this comment
> @chriswalz `bit` is released to gobinaries.com by goreleaser automatically, right?
> 
> If so, I'll integrate brew deployment cycle with goreleaser too after I tested manual way

Goreleaser and gobinaries.com are separate. I run Goreleaser locally and it uploads binaries to this page https://github.com/chriswalz/bit/releases

**Comment by imcvampire** [comment]
Hi? Any update?

**Comment by roeniss** [comment]
@chriswalz @dawidd6 @imcvampire and other thumb-uppers, sorry for late.

After a week, I found that this task is hard to me. My personal job has became serious more than I thought.

So I'll leave this task so other people can take this instead of me.

I will keep trying to do this until other comes up to help but not sure when it would be possible. Sorry for bad news.

**Comment by chriswalz** [comment]
I'll look into it

**Comment by chriswalz** [comment]
I haven't gotten homebrew working yet. 

However,  **you can now update** the cli using `bit update`. This command is available starting in `v0.7.5`

This alleviates most of the need for homebrew

**Comment by crunchtime-ali** [comment]
Here you go https://github.com/Homebrew/homebrew-core/pull/63508
I would like a better test-case though as this one is basically just testing git functionality.

@chriswalz One its merged I will add a pull request to your homebrew tap adding a tap migration.

**Comment by chriswalz** [comment]
@crunchtime-ali thanks again.

to install, use `brew install bit-git`

**Comment by crunchtime-ali** [comment]
@chriswalz You're welcome. Bit is a cool tool I demonstrated yesterday in a Kubernetes workshop. It is helpful for people getting to grips with git's CLI.

Regarding https://github.com/chriswalz/homebrew-bit. You can migrate taps (e.g. for your personal tap to homebrew-core) by adding a file called `tap_migrations.json` to your tap (here is an example https://github.com/argoproj/homebrew-tap/blob/master/tap_migrations.json).

However, AFAIK the file does not support renaming your formula. Therefore, I think it is best to archive your tap project or delete it altogether. You also should remove it from your [.goreleaser.yml](https://github.com/chriswalz/bit/blob/master/.goreleaser.yml).

Of course you can also keep your tap but it doesn't serve much of a purpose because the awesome homebrew-community will take care of updating the official tap and maintaining it.

**Comment by imcvampire** [comment]
Hi all,

After trying the new tap, I found a problem. We have a conflict with a program named `bit`

```Error: Cannot install bit-git because conflicting formulae are installed.
  bit: because both install `bit` binaries

Please `brew unlink bit` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side effects in the
resulting software.```

https://bit.dev/

**Comment by chriswalz** [comment]
@crunchtime-ali Thanks for the call out – I've archived the project and deleted the brew section from `goreleaser`

Formula page for the curious
https://formulae.brew.sh/formula/bit-git

### Resolving bit name conflict
As for @imcvampire that's unfortunate to see the name conflict. There's probably a work around that can be implemented as part of homebrew (maybe @crunchtime-ali  would know) however in the meantime you'd have to download the binary manually from the releases page and name it to something else. Alternatively you could rename the existing conflicting bit binary and then run `brew install bit-git`

**Comment by crunchtime-ali** [comment]
@imcvampire Besides using `brew unlink/link` every time you need the other application there is AFAIK no way to properly handle this with Homebrew. You are probably better off installing one of them manually as @chriswalz suggested.
