### ISSUE TITLE
Extra space before committed message using 'bit save "commit message"'

### ISSUE THREAD

**Issue by liangshb** [chriswalz/bit#94]
**Describe the bug**
Extra space before committed message using 'bit save "commit message"'

**To Reproduce**
1. modify something
2. bit save "commit message"
3. git log --oneline

**Screenshots**
![Snipaste_2020-11-26_15-24-43](https://user-images.githubusercontent.com/29915175/100320114-a4c82480-2fb8-11eb-9f8e-977f9a07f82f.png)
![Snipaste_2020-11-26_15-25-53](https://user-images.githubusercontent.com/29915175/100320127-a72a7e80-2fb8-11eb-8340-c11e445623fe.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Terminal: WSL in Windows Terminal
 - Shell: zsh
and
- OS: Win7
- Terminal: Git Bash
- Shell: Bash

**Comment by aditya520** [comment]
I can't reproduce it on Ubuntu 18.04

**Comment by liangshb** [comment]
![image](https://user-images.githubusercontent.com/29915175/106695241-28d00580-6615-11eb-81d9-320343857adc.png)
I reproduced it on UOS 20

**Comment by chriswalz** [comment]
I've been working on adding significantly more suggestions for lesser used commands so I haven't gotten around to this. 

I hope to resolve this soon assuming I can replicate it

**Comment by chriswalz** [comment]
@liangshb please run `bit update` to update to version 0.9.12. Let me know if this is fixed

**Comment by liangshb** [comment]
![image](https://user-images.githubusercontent.com/29915175/106700769-7a31c200-6620-11eb-8d17-157a6d88f492.png)

Problem solved, thanks

**Comment by chriswalz** [comment]
Great!
